### ISSUE TITLE
lightline support

### ISSUE THREAD

**Issue by brainplot** [wojciechkepka/vim-github-dark#1]
Any plans to support [lightline](https://github.com/itchyny/lightline.vim)?

**Comment by vv9k** [comment]
I added some initial colors in a4ed9c016b131370eea5991ec1d03e3310017c64 but i'm unable to test it. Lightline says that it `Could not load colorscheme ghdark`

**Comment by vv9k** [comment]
Ok, now it definitely works as of 35171f029bee98fbd8733366140d11daa0bd7089 . I have tested it myself :) enjoy!
