### ISSUE TITLE
Unreadable cursor color

### ISSUE THREAD

**Issue by ianyepan** [wojciechkepka/vim-github-dark#2]
The current cursor color is set to base_1, which is almost the same as the background color. I believe it's a typo and you intended the cursor to be more visible.

**Comment by vv9k** [comment]
For some reason `Cursor` does not seem to have any effect for me. I tried changing it to `base4` and other colors but it still looks the same:

![cursor](https://user-images.githubusercontent.com/46892771/117564337-d71f9700-b0ab-11eb-8d9a-a72c4e63b5f5.png)

**Comment by vv9k** [comment]
I've updated the colors in efa9f9e, perhaps it should look more readable now

**Comment by ianyepan** [comment]
Ah, I should have added that I was using GVim. Maybe that's the reason!

**Comment by vv9k** [comment]
It looks alright now in GVim too :)

![image](https://user-images.githubusercontent.com/46892771/117565963-5add8180-b0b4-11eb-9796-b75acd196a0b.png)

**Comment by vv9k** [comment]
And as of 734ed46 the letters under the cursor should also be visible
![image](https://user-images.githubusercontent.com/46892771/117566105-f5d65b80-b0b4-11eb-8c0d-32857737d599.png)

**Comment by ianyepan** [comment]
Cheers man, appreciate the effort.
Closing issue
