### ISSUE TITLE
Support color for markdown docs

### ISSUE THREAD

**Issue by AndyHoang** [wojciechkepka/vim-github-dark#3]
Github don't need support coloring for markdown docs because the docs was rendered as html when we open the file online

While doing coding and write md file is quite a daily work to us.

I think support coloring for md docs is make sense in this situation

**Comment by vv9k** [comment]
Actually GitHub does support coloring markdown docs and thats where the current colors are mostly from:
<img width="1212" alt="Screenshot 2021-05-12 at 05 39 07" src="https://user-images.githubusercontent.com/46892771/117914880-716a1f80-b2e4-11eb-8020-2f8de16b6e34.png">



But I do agree that perhaps in this case it would be better to provide a more custom and easy for the eyes colors

**Comment by vv9k** [comment]
So this is what I came up with initially. You can check it out by updating the plugin.

![image](https://user-images.githubusercontent.com/46892771/117986079-93da5800-b339-11eb-9417-b3ed158e747e.png)

**Comment by AndyHoang** [comment]
Very nice, thanks
