### ISSUE TITLE
colorscheme error after update

### ISSUE THREAD

**Issue by steelvelveteen** [wojciechkepka/vim-github-dark#4]
Vim detects erro while processing init.vim config file at line where colorscheme is set to ghdark. After pressing Enter to continue if I run 
:colorscheme ghdark it says E185: Cannot find color scheme 'ghdark'.
I'm wondering where is the actual code?!?

**Comment by vv9k** [comment]
I mistakenly made changes in the wrong directory... I brought back the last commit, I hope it will resolve the issue :smile:

**Comment by steelvelveteen** [comment]
All good now, thanks!
